"""Pure helper modules for UT Breakout research and validation."""

from .indicators import (
    bollinger_width_percentile,
    keltner_squeeze_state,
    previous_donchian,
    rolling_percentile_rank,
)
from .coinselector import (
    build_base_candidate,
    build_selection_report,
    default_coin_selector_config,
    finalize_candidate,
    market_is_tradifi_perpetual,
    normalize_custom_symbol,
    normalize_custom_symbols,
    rank_candidates,
    sector_tags_for_symbol,
)
from .research import format_research_summary, summarize_diagnostic_events
from .risk import calculate_risk_plan
from .timeframe import HTF_MAP, select_adaptive_timeframe
from .micro_auto import (
    MICRO_AUTO_STRATEGY_KEY,
    assess_micro_market_feasibility,
    build_micro_entry_plan,
    default_micro_auto_config,
    normalize_micro_auto_config,
)
from .quant_config import default_quant_config
from .regime import RegimeAction, classify_market_regime, classify_regime, default_regime_config, regime_action
from .meta import (
    GateDecision,
    apply_meta_gate_to_risk,
    build_meta_features,
    decide_meta_trade,
    estimate_meta_probability,
    evaluate_meta_label,
    label_from_barrier_outcome,
    meta_label_gate,
    probability_to_size_multiplier,
    triple_barrier_label,
)
from .sizing import build_position_risk_multiplier, calculate_adaptive_risk_pct, default_sizing_config
from .portfolio import evaluate_portfolio_risk, default_portfolio_config
from .performance import (
    apply_multiple_testing_penalty,
    calculate_performance_metrics,
    deflated_sharpe_proxy,
    group_performance,
    passes_oos_rules,
    passes_train_rules,
    pbo_proxy,
    walk_forward_splits,
)
from .exit_policy import (
    DEFAULT_EXIT_POLICY,
    EXIT_POLICY_CANDIDATES,
    ExitPolicy,
    ExitSignal,
    PolicyStats,
    PolicyStatsStore,
    TpConfig,
    build_default_exit_policy,
    build_exit_policy,
    build_volatility_adaptive_tp,
    choose_exit_policy,
    evaluate_signal_invalid_exit,
    evaluate_time_stop,
    rank_exit_policies,
)
from .adaptive import (
    build_dynamic_chandelier_stop,
    build_strategy_adaptation,
    build_strategy_quality_score,
    build_trend_health_score,
    evaluate_shadow_runner_exit,
    evaluate_shadow_triple_barrier,
    summarize_runner_outcomes,
    summarize_shadow_outcomes,
)

__all__ = [
    "build_base_candidate",
    "build_selection_report",
    "calculate_risk_plan",
    "default_coin_selector_config",
    "finalize_candidate",
    "market_is_tradifi_perpetual",
    "format_research_summary",
    "HTF_MAP",
    "normalize_custom_symbol",
    "normalize_custom_symbols",
    "MICRO_AUTO_STRATEGY_KEY",
    "assess_micro_market_feasibility",
    "build_micro_entry_plan",
    "previous_donchian",
    "rolling_percentile_rank",
    "bollinger_width_percentile",
    "keltner_squeeze_state",
    "default_micro_auto_config",
    "default_quant_config",
    "DEFAULT_EXIT_POLICY",
    "EXIT_POLICY_CANDIDATES",
    "ExitPolicy",
    "ExitSignal",
    "PolicyStats",
    "PolicyStatsStore",
    "TpConfig",
    "build_default_exit_policy",
    "build_exit_policy",
    "build_volatility_adaptive_tp",
    "choose_exit_policy",
    "evaluate_signal_invalid_exit",
    "evaluate_time_stop",
    "rank_exit_policies",
    "rank_candidates",
    "normalize_micro_auto_config",
    "sector_tags_for_symbol",
    "select_adaptive_timeframe",
    "summarize_diagnostic_events",
    "build_strategy_adaptation",
    "build_strategy_quality_score",
    "build_dynamic_chandelier_stop",
    "build_trend_health_score",
    "evaluate_shadow_runner_exit",
    "evaluate_shadow_triple_barrier",
    "summarize_runner_outcomes",
    "summarize_shadow_outcomes",
    "classify_market_regime",
    "classify_regime",
    "regime_action",
    "RegimeAction",
    "default_regime_config",
    "GateDecision",
    "build_meta_features",
    "decide_meta_trade",
    "estimate_meta_probability",
    "evaluate_meta_label",
    "label_from_barrier_outcome",
    "meta_label_gate",
    "probability_to_size_multiplier",
    "triple_barrier_label",
    "apply_meta_gate_to_risk",
    "build_position_risk_multiplier",
    "calculate_adaptive_risk_pct",
    "default_sizing_config",
    "evaluate_portfolio_risk",
    "default_portfolio_config",
    "calculate_performance_metrics",
    "passes_train_rules",
    "passes_oos_rules",
    "apply_multiple_testing_penalty",
    "deflated_sharpe_proxy",
    "pbo_proxy",
    "group_performance",
    "walk_forward_splits",
]
